
#backend
services:
  backend: 
    build: ./backend
    container_name: mern-backend
    ports:
      - '5001:5000' #map port ในเครื่องกับ container
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - db

#frontend
  frontend:
    build: ./frontend
    container_name: mern-frontend
    ports:
    - '5174:5173'
    volumes:
    - ./frontend:/app
    - /app/node_modules
    depends_on:
    - backend

#database
  db:
    image: mysql:latest
    container_name: mern-db
    ports:
    - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project_db
    volumes:
    - db_data:/var/lib/mysql

# กำหนด volumes ที่ใช้
volumes:
  db_data: